version: '3.9'
metadata:
  schemaVersion: 2.2.0
services:
  web:
    image: amrmahmoud377/backend
    container_name: clinicbackendcontainer
    environment:
      - MONGO_URL=mongodb://mongodb_container:27017
      - DB_NAME=clinic_reservation
    ports:
      - "8000:8000"
    depends_on:
      - mongo
  mongo:
    image: amrmahmoud377/database
    container_name: mongodb_container
    ports:
      - "27017:27017"
