version: '3.9'

services:
  web:
    image: clinicbackend
    container_name: clinicbackendcontainer
    environment:
      - MONGO_URL=mongodb://mongodb_container:27017
      - DB_NAME=clinic_reservation
    ports:
      - "8000:8000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongodb_container
    ports:
      - "27017:27017"