version: 3.9

services:
  django:
    image: django-docker:0.0.1
    build: .
    ports:
      - "8000:8000"
  mongo:
    image: mongo
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ""
    ports:
      - "27017:27017"